### ISSUE TITLE
Program neobsahuje warnings

### ISSUE THREAD

**Issue by fan1x** [ZuzkaU/NPRG030#1]
![e1](https://user-images.githubusercontent.com/2750870/64890984-08468a80-d671-11e9-9134-5fc467188963.png)

**Comment by ZuzkaU** [comment]
Přidala jsem tam {$Warnings On}, jestli je to to, co myslíš? A smazala jsem nepoužité proměnné, před kterými to teď varovalo

**Comment by fan1x** [comment]
`{$Warnings On}` jsem neměl na mysli, každopadně je vždy dobré překládat program se zapnutými warnings a hlavně všechny zmíněné warnings odstranit. 
Jsou to upozornění od překladače, že něco může být špatně...
