### ISSUE TITLE
Program validuje všechny vstupy

### ISSUE THREAD

**Issue by fan1x** [ZuzkaU/NPRG030#2]
Pro zákeřné vstupy program spadne (typicky zkouším okrajové případy a nebo třeba špatné typy)

**Comment by fan1x** [comment]
Doporučuji vytvořit funkci na načítání vstupů, která  načte vstup do stringu, pak se pokusí převést string na číslo `StrToInt(), ...` a pak ještě zkontrolovat horní a spodní hranici a je to. 
Něco jako:
```
function str2int(strValue: string, lowerBound: integer, upperBound: integer, var intValue: integer): boolean;
begin
  Try
    intValue = StrToInt(strValue);
    return lowerBound < intValue AND intValue <= upperBound;
  except
    On E : EConvertError do
     return false;
  end;
end.
```

**Comment by fan1x** [comment]
Nebo můžeš rovnou použít výjimky, ale asi je lepší to zpracovat pomocí `if`

**Comment by ZuzkaU** [comment]
Hotovo
