### ISSUE TITLE
Nemohly by se serie prekryvat?

### ISSUE THREAD

**Issue by fan1x** [ZuzkaU/NPRG030#7]
Pokud neni dostatecny cas na serii, nemohly by se prekryvat?

**Comment by ZuzkaU** [comment]
Série se překrývají, když je potřeba. Je to nastavené tak, že když se série skládá třeba z úkolů A, B a C a každý z nich trvá 10 dní, tak minimální čas na jednu sérii je 30 dní a urychlit to nejde (tady jsem opravila +-jedničkovou chybu, aby to fungovalo i když ten čas bude takto přesně na den). Když mám ale třeba 3 série, tak na to stačí 32 dní, když každá další série začne o jeden den později než ta předchozí a budou se překrývat. Minimální potřebný čas na celý rozvrh je tedy délka jedné série + počet sérií-1 (pokud budou začínat o den později) + dostatečný buffer na to, pokud by se nějaké dva datumy překrývaly - pak se to celé posune dozadu, protože je to nastavené tak, aby nebyly žádné dva deadliny ve stejný den).
