### ISSUE TITLE
Použít dynamická pole

### ISSUE THREAD

**Issue by fan1x** [ZuzkaU/NPRG030#9]
Ony byly komentáře #4 a #6  naražka na to, proč jsi nepoužila dynamická pole - uživatel by neměl být omezen nějakou konstantou pokud to nemá rozumný důvod. Zkus to tedy prosím předělat na použití dynamických polí. 
Jinak, není nutné implementovat vlastní dynamické pole (čistý pascal to asi neumí?) nebo spoják. Klidně použí rozšíření free pascalu (např. https://wiki.freepascal.org/Dynamic_array)

**Comment by ZuzkaU** [comment]
Hotovo
